return require('packer').startup(function()
    use 'wbthomason/packer.nvim'
    use 'neovim/nvim-lspconfig'
    use 'kyazdani42/nvim-web-devicons'
    use 'famiu/feline.nvim'
    use 'emi2k01/nord-vim'
    use 'hrsh7th/nvim-compe'
    use 'hrsh7th/vim-vsnip'
    use 'hrsh7th/vim-vsnip-integ'
    use 'junegunn/fzf.vim'
    use 'preservim/nerdtree'
    use 'mbbill/undotree'
    use 'mg979/vim-visual-multi'
    use 'nvim-treesitter/nvim-treesitter'
    use 'tpope/vim-fugitive'
    use 'andweeb/presence.nvim'
    use 'easymotion/vim-easymotion'
end)
